version: 2.1

orbs:
  sign-packages: opennms/sign-packages@2.2.0

executors:
  build-executor:
    docker:
      - image: circleci/openjdk:8u212-jdk-stretch
        environment:
          MAVEN_OPTS: -Xmx1g

workflows:
  build-deploy:
    jobs:
      - build:
          context: "OpenNMS Build"
      - deploy:
          context: "OSSRH Principal"


jobs:
  build:
    executor: build-executor
    steps:
      - checkout

      - run:
          name: Run the tests
          command: |
            mvn -DskipITs=false clean install test integration-test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - sign-packages/install-deb-dependencies:
          skip_if_forked_pr: true
          use_sudo: true

      - sign-packages/setup-env:
          skip_if_forked_pr: true

#      - run:
#         name: Upload snapshot
#          command: |
#            mvn -Prelease -DskipTests clean deploy

      # Save dependency cache
      - save_cache:
          paths:
            - ~/.m2
            - ~/.gnupg
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - store_test_results:
          path: ~/junit

      - persist_to_workspace:
          root: ~/
          paths:
            - project

  deploy:
    executor: build-executor
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Upload snapshot
          command: |
            mvn -DskipTests -Dmaven.verify.skip=true -Dmaven.install.skip=true deploy
